name: "Forked - Merge Pull Requests"
description: "Origin action: https://github.com/pascalgn/automerge-action"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-pull-request"
  color: "blue"
